export const className = {
  wrapper: 'space-y-1',
  label: 'block text-sm font-medium text-gray-700',
  inputContainer: 'relative',
  base: 'appearance-none relative block w-full px-3 py-2 border placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm',
  error: 'border-red-300 focus:ring-red-500 focus:border-red-500',
  normal: 'border-gray-300',
  iconStart: 'pl-10',
  iconEnd: 'pr-10',
  iconWrapper: 'absolute inset-y-0 flex items-center pointer-events-none',
  iconStartWrapper: 'left-0 pl-3',
  iconEndWrapper: 'right-0 pr-3',
  errorMessage: 'text-sm text-red-600',
  helperText: 'text-sm text-gray-500',
};
